---
- name: Docker Image Build and Push
  hosts: ansible_host
  gather_facts: false

  tasks:
  - name: Build Docker Image 
    command: docker image build -t aicore00/mywebapp .
  - name: Login to Docker Hub
    command: docker login
  - name: Push Image to Docker Hub
    command: docker push aicore00/mywebapp
  - name: Remove Local Image
    command: docker image rm aicore00/mywebapp tomcat:9-jdk11

- name: Run Docker Container
  hosts: docker_host
  gather_facts: false
  tasks:
  - name: Stop Existed Container
    command: docker stop tomcat-mywebapp
    ignore_errors: true
  - name: Remove Existed Container
    command: docker rm tomcat-mywebapp
    ignore_errors: true
  - name: Run Container
    command: docker run -d --name tomcat-mywebapp -p 8080:8080 aicore00/mywebapp
